---
title: "strings_and_factors"
author: "Yuqi Miao"
date: "10/15/2019"
output: html_document
---

```{r}
library(tidyverse)
library(rvest)
```


# Strings and regex

```{r}
string_vec = c("my", "name", "is", "Yuqi")
str_detect(string_vec, "Yuqi")
str_detect(string_vec, "Yu")
### ??
str_replace(string_vec, "Yuqi", "YuQi")
str_replace(string_vec, "Y", "Yuqi")

```

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )

str_detect(string_vec, "^i think") ## ^ start with

str_detect(string_vec, "i think$") ## $ end with

string_vec = c(
  "Y'all remember Pres. HW Bush?",
  "I saw a green bush",
  "BBQ and Bushwalking at Molonglo Gorge",
  "BUSH -- LIVE IN CONCERT!!"
  )
str_detect(string_vec,"[Bb]ush") ## [ ] within are all okay
```


```{r}
string_vec = c(
  '7th inning stretch',
  '1st half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )
str_detect(string_vec, "^[0-9][a-zA-Z]") 
```


```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )
str_detect(string_vec, "7.11") 
```


```{r}
string_vec = c(
  'The CI is \ [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )
str_detect(string_vec, "\\[")
```

```{r}
pulse_data = 
  haven::read_sas("public_pulse_data.sas7bdat") %>%
  janitor::clean_names() %>%
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    names_prefix = "bdi_score_",
    values_to = "bdi") %>%
  select(id, visit, everything()) %>%
  mutate(
    visit = str_replace(visit, "bl", "00m"),
    visit = fct_relevel(visit, str_c(c("00", "01", "06", "12"), "m")),
    age = round(age,1),
    bdi = round(bdi,0)
    ) %>% ## str_c 
  arrange(id, visit)

print(pulse_data, n = 12)

```




```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
table_marj = 
  read_html(nsduh_url) %>%
  html_nodes(css = "table") %>% 
  .[[1]] %>%
  html_table() %>%
  slice(-1) %>%
  as_tibble() %>% 
  select(-contains("P Value")) %>% 
  pivot_longer(
    cols = -State,
    names_to = "category",
    values_to = "drug_use"
  ) %>% 
  separate(col = category, into = c("age", "year") ,sep = "\\(" ) %>% 
  mutate(
    year = str_replace(year,"\\)",""), ## use replace to remove unuseful characters
    drug_use = str_replace(drug_use, "[a-z]$",""),## remember to specify the location of the goal characters
    drug_use = as.numeric(drug_use)
  )

table_marj %>% 
  filter(age %in% c("18-25", "12-17","26+") )%>% 
  mutate(state = fct_reorder(State, drug_use)) %>% 
  ggplot(aes(x = state, y = drug_use,color = year,group = year )) +
    geom_line() +
    facet_grid(.~age)+
    theme(axis.text.x = element_text(angle = 90, hjust = 1))
  
  
  
```


## Skip in class troublr nodes
```{r}
url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="
urls = str_c(url_base, 1:5)
read_html(urls[1]) %>% 
  html_nodes("#cm_cr-review_list .review-title") %>%
  html_text()

read_html(urls[2]) %>% 
  html_nodes("#cm_cr-review_list .review-title") %>%
  html_text()


```

```{r}
##url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewer##Type=avp_only_reviews&sortBy=recent&pageNumber="
##url_review = str_c(url_base, 1:5)
##review = vector("list", length = 5)
##for (i in 1:5) {
##  review[i] = 
##    read_html(url_review[i]) %>% 
##    html_nodes("#cm_cr-review_list .review-title") %>% 
##    html_text()
##}

```



# Factor

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

```


## fct_relevel()

```{r}
weather_df %>%
  mutate(name = forcats::fct_relevel(name, c("Waikiki_HA", "CentralPark_NY", "Waterhole_WA"))) %>% 
  ggplot(aes(x = name, y = tmax)) + 
  geom_violin(aes(fill = name), color = "blue", alpha = .5) + 
  theme(legend.position = "bottom")


```

```{r}
weather_df %>%
  lm(tmax ~ name, data = .)

weather_df %>%
  mutate(name = forcats::fct_relevel(name, c("Waikiki_HA", "CentralPark_NY", "Waterhole_WA"))) %>% 
  lm(tmax ~ name, data = .)

## change the reference level will change the intercept and coefficient of each indicator var.

```



## fct_reorder()

```{r}
weather_df %>%
  mutate(name = forcats::fct_reorder(name, tmax)) %>% 
  ggplot(aes(x = name, y = tmax)) + 
  geom_violin(aes(fill = name), color = "blue", alpha = .5) + 
  theme(legend.position = "bottom")

```

















